"""VerifierEngine — post-audit rule-based issue detection.

Runs after the main LLM audit pipeline to catch specific known
false-negative patterns that the model systematically misses.
"""

import logging
from typing import Dict, List

from backend.verifiers.verifiers import (
    verify_as_is_no_warranty,
    verify_asymmetric_termination,
    verify_single_trigger_coc,
)

logger = logging.getLogger(__name__)

VERIFIERS = [
    verify_as_is_no_warranty,
    verify_asymmetric_termination,
    verify_single_trigger_coc,
]


def _normalize_title(title: str) -> str:
    return (title or "").strip().lower()


def _is_duplicate(new_issue: dict, existing_issues: List[dict]) -> bool:
    """Check if a verifier finding duplicates an existing pipeline finding.
    
    An issue is considered duplicate if another issue exists with the
    same title AND same category (exact, case-insensitive). This allows
    the verifier to fix mis-categorized findings (same title, right category).
    """
    new_title = _normalize_title(new_issue.get("issue_title", ""))
    new_cat = _normalize_title(new_issue.get("category", ""))
    if not new_title:
        return False
    for existing in existing_issues:
        existing_title = _normalize_title(existing.get("issue_title", ""))
        existing_cat = _normalize_title(existing.get("category", ""))
        if existing_title == new_title and existing_cat == new_cat:
            return True
    return False


def run_verifiers(
    doc_text: str,
    existing_issues: List[dict],
) -> List[Dict]:
    """Run all verifiers against the document text.
    
    Args:
        doc_text: The full document text.
        existing_issues: Issues already generated by the main pipeline.
        
    Returns:
        List of new issue dicts to append (already deduplicated).
    """
    if not doc_text or not doc_text.strip():
        return []
    new_issues = []
    for verifier_fn in VERIFIERS:
        try:
            result = verifier_fn(doc_text)
            if result is None:
                continue
            if _is_duplicate(result, existing_issues):
                logger.info(
                    "[Verifier] Skipped duplicate: %s",
                    result.get("issue_title", ""),
                )
                continue
            if _is_duplicate(result, new_issues):
                continue
            new_issues.append(result)
            logger.info(
                "[Verifier] Generated: %s (severity=%s, category=%s)",
                result.get("issue_title", ""),
                result.get("severity", ""),
                result.get("category", ""),
            )
        except Exception as e:
            logger.error(
                "[Verifier] Error in %s: %s",
                verifier_fn.__name__,
                e,
            )
    return new_issues
